apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/venkatamatrix/spring-boot-rest-prometheus-java11:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/venkatamatrix/spring-boot-rest-prometheus-java11:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-boot-rest-prometheus-java11
        chartPath: charts/spring-boot-rest-prometheus-java11
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/venkatamatrix/spring-boot-rest-prometheus-java11'
          image.tag: '{{.DIGEST_HEX}}'
